### ISSUE TITLE
Without page refresh nothing change after cookie is set.

### ISSUE THREAD

**Issue by farynaio** [andrezimpel/gatsby-plugin-gdpr-cookies#32] opened 2020-12-29 10:09 UTC
As described in title.

**Comment by andrezimpel** [comment] 2021-01-13 06:43
Hey @farynaio which version are you using? Because this should actually work. You have to follow these instructions: https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies#initialize-and-track.

**Comment by ahmadkhalaf1** [comment] 2021-01-27 13:19
@andrezimpel Hello , i think this initialize is new or i never saw it before , so today i tried it out , and for some reason its not working as expected , what am i doing wrong here?
```
inside gatsby-config.js
{
      resolve: `gatsby-plugin-gdpr-cookies`,
      options: {
        googleTagManager: {
          trackingId: process.env.GTM_PROPERTY, // leave empty if you want to disable the tracker
          cookieName: 'gatsbyConsentMandatory', // // here can you change the cookie name
          dataLayerName: 'dataLayer', // default
          defaultDataLayer: { platform: 'gatsby' },
        },
        environments: ['production', 'development'],
      },
    },

inside consent.tsx
import { useLocation } from '@reach/router';
import { initializeAndTrack } from 'gatsby-plugin-gdpr-cookies';
const location = useLocation();

 const handleCookieAccept = () => {
 initializeAndTrack(location);
 }
 <Button  onClick={() => handleCookieAccept()}> Accept  </Button>
 
 without user clicking accept i can see that GTM is loaded in my network and i can access datalayer in my browser console as well .

**Comment by andrezimpel** [comment] 2021-02-05 09:40
@ahmadkhalaf1 Do you also see data being received? The scripts are being implemented ssr but should NOT send data - only include the script. I had to wrap my head around this with GA4 and gtag too.

**Comment by andrezimpel** [comment] 2021-02-05 13:45
Duplicate of #30

**Closed by andrezimpel** 2021-02-05 13:45 UTC
